<?php

namespace App\Http\Requests\Web\Admin;

use App\Http\Repositories\Web\Admin\ProductRepository;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class DeleteProductRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    protected $stopOnFirstFailure=true;
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return ProductRepository::DeleteProductRule();
    }
    protected function failedValidation(Validator $validator)
    {
        \Alert::warning('please chose correct product');
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
    public function validationData()
    {
         return array_merge(
            parent::validationData(),
            ['product_id'=>\Request::route('product_id')]
        );
    }

}
