<?php

namespace App\Http\Requests\Web\Admin;

use App\Http\Repositories\Web\Admin\ProductRepository;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class DeleteProductReviewRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return ProductRepository::DeleteProductReviewRules();
    }

    public function validationData()
    {

        return array_merge(
            parent::validationData(),
            ['productReview_id'=>$this->route('product_review_id')]
        );
    }
    protected function failedValidation(Validator $validator)
    {
        \Alert::warning('Invalid product Review');
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
