<?php

namespace App\Http\Requests;

use App\Http\Repositories\Web\Customer\CartItemRepository;
use App\Models\CartItem;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class addCartItemRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */

    protected $stopOnFirstFailure=true;
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */

    public function rules()
    {
        return CartItemRepository::addCartItemRules();
    }

    protected function failedValidation(Validator $validator)
    {
        \Alert::alert('خطاء', $validator->errors()->all() );
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }

}
